pentaho-xul-core/build-res/subfloor.xml, pentaho-xul-gwt/build-res/subfloor.xml, pentaho-xul-html/build-res/subfloor.xml, pentaho-xul-swing/build-res/subfloor.xml, pentaho-xul-swt/build-res/subfloor.xml
Merge of master into future-develop
=> Auto-Merge refreshing development branch

pentaho-xul-swt/src/org/pentaho/ui/xul/swt/tags/SwtTextbox.java
Mark type field as protected for use in subclasses
=> [PDI-13770] Password Field Consistency

.gitignore, pentaho-xul-swt/src/org/pentaho/ui/xul/swt/tags/SwtButton.java, pentaho-xul-swt/test-src/org/pentaho/ui/xul/test/swt/SwtButtonTest.java, pentaho-xul-swt/test-src/resource/documents/imageButton.xul
Render SwtButton in case both image and label are set.
@hudak
=> [BACKLOG-5053] Data services dialog is missing help button icon

pentaho-xul-swt/src/org/pentaho/ui/xul/swt/tags/SwtDialog.java
Also a couple checkstyle changes
=> [COMMONS-134] XUL SWT dialogs don't support no-resize

pentaho-xul-swt/src/org/pentaho/ui/xul/swt/tags/treeutil/XulTableColumnLabelProvider.java
Temporary fix for scheduler and data-services-server plugins failing on
OSX 10.11.
=> PDI-14470 Workaround for spoon failures on OSX 10.11

pentaho-xul-core/src/org/pentaho/ui/xul/impl/AbstractXulLoader.java, pentaho-xul-core/src/org/pentaho/ui/xul/impl/XulWindowContainer.java, pentaho-xul-core/src/org/pentaho/ui/xul/util/XmlParserFactoryProducer.java
@mkambol, @mbatchelor, @dkincade, could please take a look? 
The pr for master is here: https://github.com/pentaho/pentaho-commons-xul/pull/113
=> [PPP-3506] - XXE Security Vulnerability in xml parsers

pentaho-xul-gwt/src/org/pentaho/ui/xul/gwt/tags/GwtLabel.java
=> [BISERVER-7633]-Text extends outside of datasource editor dialog

pentaho-xul-gwt/src/org/pentaho/ui/xul/gwt/tags/GwtMessageBox.java
@pentaho/millenniumfalcon please review.
=> [BACKLOG-17350] Right align message box button

pentaho-xul-core/build-res/subfloor.xml, pentaho-xul-gwt/build-res/subfloor.xml, pentaho-xul-html/build-res/subfloor.xml, pentaho-xul-swing/build-res/subfloor.xml, pentaho-xul-swt/build-res/subfloor.xml
WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!
=> [ENGOPS-3650] change Pentaho to Hitachi Vantara and update copyright date

gwt/pom.xml
@lgrill-pentaho @emartin-pentaho
=> [BACKLOG-22034] fix version properties

swt/src/main/java/org/pentaho/ui/xul/swt/tags/SwtTree.java
https://github.com/pentaho/pentaho-kettle/pull/5218
=> [BACKLOG-22287] Lazy loading of folders in Repository Explorer

core/pom.xml, core/src/main/java/org/pentaho/ui/xul/impl/AbstractXulLoader.java, html/pom.xml, pom.xml, swing/pom.xml, swt/pom.xml
This is one of a series of PRs. See pentaho/maven-parent-poms#70 for the complete list and more details. **Do not merge until further notice!**
@graimundo
=> [PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

swt/src/main/java/org/pentaho/ui/xul/swt/tags/SwtDialog.java
This reverts commit c8efa0b68f96242af6ecbb89edb381f4f1c7aaf5.
=> Revert "[BACKLOG-26961] avoid extra windows from missing xul parent shell"

swing/src/main/java/org/pentaho/ui/xul/swing/tags/SwingTextbox.java
also a few of the safer sonar fixes.
Line 207 fixes the issue.  all the rest are sonar cleanup.
=> [BACKLOG-31134] - letting OS decided on password field height

swt/pom.xml
=> [CUST-249] Updating pom files to match CUST version

swt/src/main/java/org/pentaho/ui/xul/jface/tags/JfaceMenuitem.java
@pminutillo @rmansoor 
@gkuntsevich
=> [PDI-18866] Mac OS X Unable to start pdi by spoon.sh

swt/pom.xml, swt/src/main/java/org/pentaho/ui/xul/swt/tags/SwtTree.java
library that prevented the gui from updating properly.  Needs a more
comprehensive fix in the future.
=> [BACKLOG-35172] Workaround for a bug discovered when upgrading the JFace

swt/pom.xml
order to avoid pulling in Java 11 artifacts.
=> [CLEANUP] Need to specify the versions of some eclipse dependencies in

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtFileUpload.java
See PR set: https://github.com/pentaho/security-web/pull/10.
@bennychow, @ddiroma please review and merge.
=> [BACKLOG-35298] Added to GwtFileUpload the ability to upload to CSRF protected endpoints

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtFileUpload.java, gwt/impl/src/main/resources/org/pentaho/ui/xul/Gwt.gwt.xml
Depends on https://github.com/pentaho/pentaho-commons-gwt-modules/pull/798.
@bennychow, @ddiroma could one of you merge these, to unblock the build?
=> [BACKLOG-35298] Fix GWT compilation problem revealed downstream

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/AbstractGwtXulComponent.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/util/GenericDialog.java
Based on top of BACKLOG-36850's https://github.com/pentaho/pentaho-commons-xul/pull/206. Please ignore its commits. Will rebase when that it is merged.
Depends on https://github.com/pentaho/pentaho-commons-gwt-modules/pull/823.
https://jira.pentaho.com/browse/BACKLOG-36964
@pentaho/hoth please review.
=> [BACKLOG-36964] Added ARIA roles support to base XUL/GWT Dialog class

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtDialog.java
Part of PR set: https://github.com/pentaho/pentaho-platform-plugin-common-ui/pull/1617.
=> [BACKLOG-36879][BACKLOG-37033][BACKLOG-37034] GWT/XUL Dialogs Default, Trap and Restore Focus

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtMenubar.java
@pentaho/wcag  , please review
=> [BACKLOG-37110]-TAB functionality on Menubar.

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtButton.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTree.java
=> [BACKLOG-36850] Focus Visible - Accessibility -  PUC Home Page – Manage Data Sources

core/src/main/java/org/pentaho/ui/xul/containers/XulDialog.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtDialog.java
=> [BACKLOG-36722] Added method to autofocus for GWTDialog

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtDialog.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/util/GenericDialog.java
=> [BACKLOG-37246] Page Zoom (AA) - Base XUL/GWT Dialog Classes - XML Attributes

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/AbstractGwtXulComponent.java
(cherry picked from commit 5a042c1d257489337c34c060e5dc43b8ba039de2)
=> [BACKLOG-36851] : Reverting changes for database dialog

core/src/main/java/org/pentaho/ui/xul/containers/XulDialog.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtButton.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtDialog.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtFileUpload.java, gwt/impl/src/main/resources/org/pentaho/ui/xul/public/xul.css
cherry-pick of https://github.com/pentaho/pentaho-commons-xul/pull/229/, https://github.com/pentaho/pentaho-commons-xul/pull/230 to master
=> [BACKLOG-36722] Cherry-pick for CSV commits

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/AbstractGwtXulComponent.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtButton.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtDeck.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtDialog.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtGrid.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtGroupBox.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtHbox.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtImage.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtLabel.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtMenuList.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtRadio.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTextbox.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtToolbarbutton.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtVbox.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/util/GenericDialog.java
@pentaho/wcag , Please review
Depends on: https://github.com/pentaho/pentaho-commons-gwt-modules/pull/929
=> [BACKLOG-36863] Page Zoom (AA) - Data Source Wizard Dialog

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/AbstractGwtXulComponent.java
@pentaho/wcag Please review
Please squash when merging
=> [BACKLOG-37581] - Fixed menubar focus order issue

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtButton.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtEditPanel.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTabPanel.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTabbox.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTree.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/util/TreeItemWidget.java
@pentaho/millenniumfalcon @pentaho/wcag please review
=> [BACKLOG-36864] Page Zoom (AA) - Data Source Model Editor Dialog

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTextbox.java
@pentaho/wcag , Please review
Depends:
- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/935
Part of PR set:
- https://github.com/pentaho/data-access/pull/1209
=> [BACKLOG-36863] Page Zoom (AA) - Data Source Wizard Dialog - Landing Dialog

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtLabel.java
https://github.com/orgs/pentaho/teams/millenniumfalcon and https://github.com/orgs/pentaho/teams/wcag please review
=> [BACKLOG-36862] - Page Zoom (AA) - Database Connection Dialog

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTree.java
@pentaho/wcag Please review
This PR is a part of 
https://github.com/pentaho/pentaho-commons-gwt-modules/pull/941
https://github.com/pentaho/data-access/pull/1211
=> [BACKLOG-36861] - Page Zoom (AA) - Manage Data Source Dialog

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTree.java
@pentaho/millenniumfalcon @pentaho/wcag please review
=> [BACKLOG-36864] Page Zoom (AA) - Make Datasource Model Editor dialog table's icons zoomable

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTextbox.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTree.java
@pentaho/wcag Please review
Merge alongside 
https://github.com/pentaho/pentaho-platform-plugin-dashboards/pull/557
https://github.com/pentaho/pentaho-commons-gwt-modules/pull/943
https://github.com/pentaho/pentaho-platform-plugin-interactive-reporting/pull/901
=> [BACKLOG-37828] Added keyboard navigation and focus visibility for Prompts panel

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtFileUpload.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtTree.java
@pentaho/wcag , please review
This PR is part of
https://github.com/pentaho/pentaho-commons-gwt-modules/pull/950
https://github.com/pentaho/data-access/pull/1217
https://github.com/pentaho/pentaho-platform/pull/5355
=> [BACKLOG-37741] Page Zoom (AA) - Data Source Wizard Dialog-CSV file type & Sql File type Subsequent Dialogs

core/pom.xml, gwt/assembly/pom.xml, gwt/impl/pom.xml, gwt/pom.xml, html/pom.xml, pom.xml, samples/xul-barcamp/build.properties, swing/pom.xml, swt/pom.xml
[CLEANUP] updated versions via release version merger
=> Merging master into wcag

swt/pom.xml
[PPP-4936]-Vulnerable Component -Guava
[PPP-4936]: https://hv-eng.atlassian.net/browse/PPP-4936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPP-4936]-Vulnerable Component -Guava

gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtFileUpload.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtGroupBox.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtListbox.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtListitem.java, gwt/impl/src/main/java/org/pentaho/ui/xul/gwt/tags/GwtMenuList.java
=> [BISERVER-14898] - Remove Deprecated Version of StringUtils

core/pom.xml, core/src/main/java/org/pentaho/ui/xul/impl/AbstractXulLoader.java, core/src/main/java/org/pentaho/ui/xul/impl/XulWindowContainer.java, core/src/main/java/org/pentaho/ui/xul/util/XmlParserFactoryProducer.java
[BACKLOG-36134]-Consolidate Redundant Secure XML Parsing code
[BACKLOG-36134]: https://hv-eng.atlassian.net/browse/BACKLOG-36134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-36134]-Consolidate Redundant Secure XML Parsing code

core/pom.xml, core/src/main/java/org/pentaho/ui/xul/impl/AbstractXulLoader.java, core/src/main/java/org/pentaho/ui/xul/impl/XulWindowContainer.java, core/src/main/java/org/pentaho/ui/xul/util/XmlParserFactoryProducer.java
[REVERT]-BACKLOG-36134-Consolidate Redundant Secure XML Parsing code
=> [REVERT]-BACKLOG-36134-Consolidate Redundant Secure XML Parsing code

gwt/impl/pom.xml, pom.xml
[BACKLOG-43935]-Fix JDK21 test pipeline(test1) test case failures
[BACKLOG-43935]: https://hv-eng.atlassian.net/browse/BACKLOG-43935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BACKLOG-43935]-Fix JDK21 test pipeline(test1) test case failures
